### ISSUE TITLE
unexpected 409 while running watch

### ISSUE THREAD

**Issue by hoghug** [Shopify/themekit#460] opened 2017-08-30 18:25 UTC
### What I expected to happen
I'm having a lot of issues the latest release. It is all tied to 
the `theme.lock` file preventing changes being uploaded. I'm having to constantly delete the theme.lock file, do a `theme upload MYFILE --force`, or restart `theme watch`. 

I am the only one working on store, is it because I switch branches? What is the ideal set up I should be doing so I don't run into this issue constantly? Any help would be greatly appreciated.

I am considering downgrading, where/how can I get an older release? 

### My Environment

OS (including version): MacOS 10.12.6 Sierra
Themekit version: ThemeKit 0.7.3 darwin/amd64
Ignore Files(if any):

<img width="679" alt="screen shot 2017-08-30 at 10 01 40 am" src="https://user-images.githubusercontent.com/6405882/29888409-b1031914-8d75-11e7-9b25-6912ad7e0a81.png">

**Comment by tanema** [comment] 2017-08-30 20:03
Hey @hoghug Yeah this could be because you change branched. Can you please provide me we the steps to reproduce. 

To downgrade you can run `theme update --version=v0.6.12`

**Comment by hoghug** [comment] 2017-08-30 20:11
thanks @tanema - I do switch branches often and we sometimes have someone else working on it, so I think for the time being I'm going to downgrade because I was okay with how we were overwriting stuff on our dev site. thank you!

**Comment by tanema** [comment] 2017-08-30 20:13
@hoghug If you can describe to me your development process and where it goes wrong, I can possibly address it. This is the future direction of themekit and I would not want you to be on an old version without updates.

**Comment by hoghug** [comment] 2017-08-30 20:50
This is for a dev site, so whatever branch I'm working I want to be pushing live updates to it using `theme watch`.

Generally, if its a prototype I'm on something other than the `master` branch. But I'll occasionally switch branches to take care of a live production tweak, so I'll go to master and could likely be editing a file that was tweaked on a different branch, thats where the conflict arises from `theme.lock`. We have 1 major CSS file, `output.css` that is compiled from multiple input `.scss` files (see screenshot from earlier). 

Its at this point I'll clear out the `theme.lock` file or do a forced `theme upload`. 

We use beanstalk for git/deployment.

**Comment by tanema** [comment] 2017-08-31 13:37
Okay I will try working on this workflow. Is it just your development environment that you don't care about tracking versions. Would you want a way to disable it for developement?

**Comment by hoghug** [comment] 2017-08-31 15:07
Yeah, that would be great. We only have themekit set up with our dev site, and when everything looks good to go, I'll do a deployment with beanstalk to push that repo to production.

**Comment by ykimura32** [comment] 2017-08-31 21:02
I'm having the same issue since I upgraded a few days ago.  I am getting a 409 conflict error when trying to upload a particular file to production.  There don't seem to be any differences prior to editing it, so not understanding why this specific file.  Will downgrade until this issue is resolved.

**Comment by hoghug** [comment] 2017-08-31 23:12
I'll go ahead and ask for @tanema , what is your workflow? Are you switching branches?

**Comment by ykimura32** [comment] 2017-08-31 23:41
Hi, I don't normally switch branches as I'm the only developer making changes to the code.  Occasionally in my absence someone will go in and make changes via the theme editor but they know not to do that because that will mess up the source control. What I normally do is commit my changes on a working branch, push it up to GitHub, then do a `theme upload` of individual files to the production environment before I create a PR and merge.  
In this particular case I thought that changes had been made to remote so I did a `theme download` in the dev environment and re-did the change, but threw the same 409 Error when I tried to re-upload to prod.  I do think it is theme.lock that may be the culprit.

**Comment by neycodes** [comment] 2017-09-03 18:44
I'm wondering if we could just gitignore the theme.lock file without adverse effect.

**Comment by rickmurt** [comment] 2017-09-05 23:28
Hi @tanema I'm having the same issue and I believe I know why:

We create a new theme version to dev on for sites and sync them up with a git branch of the same name.  So 1.7 may be live, and 1.8 is the development version.

Next in the workflow, once 1.8 is ready, I push 1.8 live via the Shopify admin panel, and then create a copy of that now live theme in the Shopify admin panel.  I rename it from "Copy of 1.8" to "1.9".  This becomes the 1.9 branch in git as well.  If I just had 1.8 checked out and I know it's up to date, I know 1.9 is a copy, so I simply create a branch, "git checkout -b 1.9" and just change the theme id in my config.yml without downloading all the files (since I just copied it, I know nothing changed).

With the 0.7 update, I've noticed that IF I don't download all of the files via "theme download", I run into this on every save.  I'm guessing because the timestamp of the files on the live theme is greater than the timestamp of my local files, even though the code is the same. 

Hope that helps!

**Comment by tanema** [comment] 2017-09-06 16:38
Hey @rickmurt thanks for this extra info, it really helps an incredible amount. I will have time to devote to looking into this tomorrow.

**Comment by tanema** [comment] 2017-09-08 19:52
Hey all 👋  can you install this patched version and verify that it works as you would expect it to? You can install it by running `theme update --version=v0.0.0-rc0.7.4`

**Comment by hoghug** [comment] 2017-09-08 20:34
Still having the same issue.

I switched branches, updated a file, and got the error.

<img width="671" alt="screen shot 2017-09-08 at 1 33 28 pm" src="https://user-images.githubusercontent.com/6405882/30230269-63ec455c-949a-11e7-854e-9ce2f3557517.png">

**Comment by tanema** [comment] 2017-09-08 20:35
@hoghug okay interesting thanks for trying it out so quickly.

**Comment by hoghug** [comment] 2017-09-08 20:41
I cleaned out my theme.lock file, it might actually be working. I'll let you know if it seems to be corrected.

**Comment by hoghug** [comment] 2017-09-11 15:10
@tanema
Update: things seem to be working much smoother now with the patch.

**Comment by ckizer** [comment] 2017-09-15 01:21
Was having the same problem. Upgrade to rc0.7.4 and emptied my theme.lock file.

**Comment by tanema** [comment] 2017-09-26 18:31
Please leave me a comment if this is still causing issues with version 0.7.5

**Comment by neycodes** [comment] 2017-10-05 20:37
I've been running 0.7.5 for the last 2 days. So far no 409 errors. Going to have some of my team members update too and see if any 409 errors pop up on their end.

**Comment by tanema** [comment] 2017-10-05 20:44
@neycodes thank you so much, I really appreciate the loop back. It is hard to get feedback on this project.

**Comment by seangeng** [comment] 2017-10-09 14:14
Hey I'm running 0.7.5 and getting the 409 error still on just a single file (product.liquid) but not others.  Any ideas?

**Comment by tanema** [comment] 2017-10-10 13:17
@seangeng Have you run `theme download templates/product.liquid` to get the most recent version of that file?

**Comment by seangeng** [comment] 2017-10-11 23:58
@tanema Oh awesome, that worked.  Thanks!

**Comment by neycodes** [comment] 2017-10-12 08:15
Update: My team all updated to 0.7.5. It's been a full week. No 409 error encountered.

**Comment by tanema** [comment] 2017-10-12 13:27
Awesome, thanks so much. Because of the positive feedback and no new reports of issues I am going to close this issue.

**Closed by tanema** 2017-10-12 13:27 UTC

**Comment by sturdynut** [comment] 2017-10-17 19:00
I know this is closed, but I had this happen today (10/17/2017) with my theme.scss.liquid file.  

I was running `theme watch --env=dev`, and seemingly randomly got a 409 conflict.  Note: I'm the only one working on this, so no one else made any changes.  I upgraded to version 0.7.5 and still had a 409 conflict.  

### Quick Dirty Fix 🤢

* `rm ./theme.lock` or just delete the contents

_Note: **This is a dirty, dirty fix**, feels wrong and I hate it, but i'm in early development on the project and don't have time to figure out why a timestamp changed somehow._

I'm happy to provide any more info to help troubleshoot / diagnose.

**Comment by tanema** [comment] 2017-10-17 19:30
@sturdynut did you download the file as well?

**Comment by sturdynut** [comment] 2017-10-17 20:12
@tanema - I did not, but I will try that next time.  Thank you!

Might be helpful to include some messaging along with the 409 conflict that there was a system update and that you just need to re-download the file.

**Comment by yifanchen** [comment] 2017-11-13 05:21
@sturdynut I have have the same problem. I don't get `There have been changes to this file made remotely` on `Prod` but on `Development`. It drives me crazy when there's no obvious errors saying what's going on. I wanted to create a workflow where my team can develop and test, then upload.

**Comment by tanema** [comment] 2017-11-13 14:39
@yifanchen If you run upload you would see the full error 

```
➜  theme upload layout/theme.liquid
09:33:40 Unexpected changes made on remote.
Diff:
        Updated Files:
                - layout/theme.liquid local:[Jul 24 10:14AM 2017] remote:[Nov 13 3:33AM 2017]

You can solve this by running 'theme download' to get the most recent copy of these files.
Running 'theme download' will overwrite any changes you have made so make sure your work is
commited to your VCS before doing so.

If you are certain that you want to overwrite any changes then use the --force flag
```

I will however add this description to the error output of the 409 so that there is no longer any confusion.

**Comment by jiaweiming** [comment] 2017-11-14 06:35
i have the same problem, theme watch --env=test works,but when i change the code and save it ,the error 409 comes,my workmates do not have this problem,only me ...help~~

**Comment by seandogg** [comment] 2018-01-05 00:16
Using `theme download [filename]` worked for me... then fired up `theme watch` and used `Cntrl + Z` in my IDE to Undo the downloaded changes and send the new updates. A bit hacky but worked in my case.

**Comment by lukehatfield** [comment] 2018-02-01 14:10
I ran `theme download [filename]` but there were no differences. I'm using SASS to enable local @imports in my `theme.scss`, then compiling to `theme.scss.liquid` that gets uploaded for the site. I only get the `409 Conflict` error when the watcher sees changes to my `theme.scss` file, not to `theme.scss.liquid`, which uploads correctly.

**Comment by scoreytime** [comment] 2018-04-15 22:26
Using `theme download [filename]` also did the trick for me. A bit hacky but it works nicely.

**Comment by aeu** [comment] 2019-02-10 11:41
The tool is telling you that the remote file has changed so you can't upload changes.  `theme download [filename]` fetches the remote.  I honestly don't see what is so "hacky" about this at all.

**Comment by CodeBrotha** [comment] 2019-02-10 16:03
@aeu if that file has any local changes, theme download erases them.
