### ISSUE TITLE
Random upload of all files upon save

### ISSUE THREAD

**Issue by ikolarov** [Shopify/themekit#576] opened 2018-09-18 14:02 UTC
### What happened

I don't know if this issue was reported but since a few versions backwards while I work on a random file and try to save it will start uploading all the files in my directory "assets", "snippets", "config", "sections" etc.. 

Because of this it usually overwrites my `settings_data.json` file and I have now the habit of deleting the file so it doesn't overwrite my settings.

### Steps to reproduce

I can't provide a steps to reproduce this issue, since this happens randomly for me. 

The issue is not present only for me but for other developers as well working on the same version of themekit and same environment as me.

This is using only the `theme watch` command.

### My Environment

OS (including version): `Windows 10`
Themekit version: `0.8.0`
Editor (including version): `Sublime Text 3`
Ignore Files(if any): `settings_data.json`

----

Has anyone experienced this issue and knows if the new prerelease fix it?

**Comment by tanema** [comment] 2018-09-18 15:07
duplicate of #519 please add your information there. Since you are also on the windows 10 OS, it seems likely that this problem is specific to windows 10. I am still under the suspicion that it may be because of a virus scanner.

**Closed by tanema** 2018-09-18 15:07 UTC
