### ISSUE TITLE
Didn't change any thing in the file but theme watch process it

### ISSUE THREAD

**Issue by besteven** [Shopify/themekit#592] opened 2018-10-27 13:58 UTC
**Describe the bug**
I'm using ThemeKit with VS Code and some time when i open the file, then click to move the cursor on file to other line, ThemeKit detech that it's a file changing and process my file.

**To Reproduce**
+ theme download to download an existing theme
+ theme watch
+ open any file and there're 2 case:
   - it automatic process this file to server when i just open the file
   - after open the file and mouse click to change the cursor position on file, it automatic process this file to server.

**Expected behavior**
I expected the file only be process to server only when i change the code & save.

**Environment (please complete the following information):**
 - OS [e.g. iOS]: Window 10
- Themekit version [e.g. v0.7.5]: v0.8.1 (the lastest version)
 - Editor [e.g. atom, sublime]: VS Code
 - Ignore: None

**Additional context**
This error also show when i just start theme watch: 
[development] processing templates/customers
[development] error loading templates/customers: requested asset is a directory

**Comment by tanema** [comment] 2018-10-29 14:23
This seems like it is a duplicate of https://github.com/Shopify/themekit/issues/519

Can you please fill out the rest of the bug template please?


**Environment (please complete the following information):**
 - OS [e.g. iOS]:
- Themekit version [e.g. v0.7.5]:
 - Editor [e.g. atom, sublime]:
 - Ignore:

**Comment by besteven** [comment] 2018-10-30 03:11
Hi Tim,
Sorry for missing the template, i've updated it. 
About the #519, i've also get that error before, when i was working using theme watch it's auto process all my project file to server. But now i'm not getting that error anymore. Now i'm just the error that i've described above.

**Comment by tanema** [comment] 2018-10-30 14:09
You can fix the `requested asset is a directory` error by updating to the prerelease with:

```theme update --version=v1.0.0-pre```

I am also closing this as a duplicate of the other issue because it seems like there is an issue with windows 10 causing many update events. Thank you for filling out the rest of the template!

**Closed by tanema** 2018-10-30 14:09 UTC
