### ISSUE TITLE
Theme watch fails with `fatal error: heapBitsSweepSpan`

### ISSUE THREAD

**Issue by zachharkey** [Shopify/themekit#195] opened 2016-09-22 16:57 UTC
I've been using themekit for a year without any issues. Then yesterday and today `theme watch` has been failing with `fatal error: heapBitsSweepSpan`

```

$ theme watch
Spawning 2 workers for pieces-6.myshopify.com
pieces-6.myshopify.com Worker #1 ready to upload local changes
pieces-6.myshopify.com Worker #0 ready to upload local changes
Received Update event on assets/timber.scss.liquid
Successfully performed Update operation for file assets/timber.scss.liquid to pieces-6.myshopify.com
Received Update event on assets/timber.scss.liquid
fatal error: heapBitsSweepSpan

runtime stack:
runtime.throw(0x50fe40, 0x11)
	/usr/local/go/src/runtime/panic.go:547 +0x90
runtime.heapBitsSweepSpan(0xc820486000, 0x66fbe1bcc8cf, 0x0, 0x700004a36da0)
	/usr/local/go/src/runtime/mbitmap.go:569 +0x3e6
runtime.(*mspan).sweep(0x99a3c8, 0x500000000, 0x200000101)
	/usr/local/go/src/runtime/mgcsweep.go:301 +0x524
runtime.sweepone(0x39b52)
	/usr/local/go/src/runtime/mgcsweep.go:112 +0x23e
runtime.gosweepone.func1()
	/usr/local/go/src/runtime/mgcsweep.go:124 +0x21
runtime.systemstack(0xc820021500)
	/usr/local/go/src/runtime/asm_amd64.s:291 +0x79
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1051

......
```

#### _[See full error message here](https://gist.github.com/zachharkey/f55bbd66f7aa6dfdc804b71ce19b79f6)..._

**Comment by zachharkey** [comment] 2016-09-22 16:59
Oh yeah, I upgraded to macOS Sierra yesterday, which may have something to do with it.

**Comment by chrisbutcher** [comment] 2016-09-22 17:31
@zachharkey Thanks! We'll determine if it's macOS Sierra related first

**Comment by Cam** [comment] 2016-09-23 00:14
I've been using ThemeKit on macOS for a few weeks now, and there do seem to be quite a few issues popping up.

Including:
- `fatal error: gc: unswept span`
- `theme watch` deletes files rather than uploading them on first save
- other seemingly swap file related issues

**Comment by tanema** [comment] 2016-09-23 13:28
@Cam can you tell us what version of OSX you are running?

**Comment by chrisbutcher** [comment] 2016-09-23 17:41
@zachharkey @Cam Please try `theme watch` with version 0.4.3 that was just released. Thanks!

**Comment by zachharkey** [comment] 2016-09-23 20:56
@chrisbutcher 0.4.3 is smooth sailing. Thank you so much!

**Comment by chrisbutcher** [comment] 2016-09-26 13:48
Nice! 🎉

**Comment by tanema** [comment] 2016-09-28 17:28
Closing since it seems this has been cleared up. Please reopen if you find the issue is still happening.

**Closed by tanema** 2016-09-28 17:28 UTC
