### ISSUE TITLE
Installing Theme Kit with Powershell throws an error

### ISSUE THREAD

**Issue by Aly-76** [Shopify/themekit#623] opened 2019-03-22 18:39 UTC
**Describe the bug**
When installing Theme Kit using Windows Powershell, after the command is entered, the terminal shows errors and fails to install. 

**To Reproduce**
1. Open Windows Powershell
2. Enter the command to install

**Expected behavior**
After the insatllation command is run, the terminal shows error and fails to install.

**Environment (please complete the following information):**
- Themekit version [e.g. v0.7.5]:
- Windows 10

**Error**
Exception calling "DownloadingString" with "1" argument(s): "The request was aborted: Coould not create SSL/TLS secure channel."

**Comment by tanema** [comment] 2019-03-22 18:55
Closing as a duplicate of https://github.com/Shopify/themekit/issues/618

**Closed by tanema** 2019-03-22 18:55 UTC
