### ISSUE TITLE
Watch command doesn't track new files

### ISSUE THREAD

**Issue by idawgik** [Shopify/themekit#608] opened 2019-01-17 23:41 UTC
**Describe the bug**
So I'm trying out themekit for a new store's theme. Previously been using Slate v0 (haven't gotten over to v1 of Slate yet, especially since we have a lot of v0 themes we need to support, and I'm not sure so far how to have both versions installed on my machine). I've created a new theme, and run the `theme watch` command in the folder.

If I make an edit to an existing file, it updates fine and pushes to Shopify.

However, if I add a new file, Themekit doesn't see it or do anything with it. It's the same whether I just create the file, copy it in from another folder, or even edit the file after it's created. 

Conversely, when I'm using Slate v0, the watch command will track and upload new files.

I am new to using Themekit, so it's entirely possible I'm just doing something wrong, but just based on the documentation for each of the tools, and past experience with Slate v0, this seems like something that isn't quite working as expected.

**To Reproduce**
1. run command 'theme watch'
2. create new file in theme folder structure

**Expected behavior**
Expect the new file to be seen and uploaded, and then watched for any future changes just like an existing file.

**Environment (please complete the following information):**
 - OS [e.g. iOS]: MacOS 10.14.3
- Themekit version [e.g. v0.7.5]: 1.0.0 Installed via Homebrew
 - Editor [e.g. atom, sublime]: Sublime Text

**Comment by tanema** [comment] 2019-01-18 01:34
Can you give me more in depth information on steps to reproduce because it all seems to work for me with both sublime text and vim.

Something super in depth, usually every detail helps. Something like this:
1. open iTerm2
1. change to directory
1. run `theme watch`
1. right click in sublime text file tree
1. click new
1. add Css file
1. save as assets/test.scss (please let me know if this happens with every file type)
1. restart themekit
1. save file again and notice change.

**Comment by idawgik** [comment] 2019-01-18 22:06
Ok, so this is definitely bizarre, but just went through and did some tests with this again today and it seems to be working...

I was able to create multiple files and have them all picked up. I'll keep an eye on it and see if anything else is missed and provide more details if so.

**Comment by tanema** [comment] 2019-01-23 21:21
If that has not happened again please let me know and we can close this issue.

**Comment by idawgik** [comment] 2019-01-23 21:23
So far everything is working fine. Looks to have been something wonky temporarily on my end. You can close.

**Comment by idawgik** [comment] 2019-01-23 22:18
Actually, I take that back. I just now ran into an issue.

I've been working on this theme today and mostly been doing css work. That was fine watching the existing file. However, I just went to start creating some section files. I created the `/sections` folder and a new `header.liquid` file in it. Themekit did not pick that new file up and upload it. Additionally, I tried making changes to the file and saving, and it didn't pick those up either.

I just did a bit of testing, and it seems to have issues watching files in a folder that doesn't exist. Since the /sections folder wasn't there initially, it didn't notice that I'd created it and then started watching inside of it.

I just closed out of themekit and created the folder with no files in it. Then restarted the watch command and created a liquid file and it was picked up fine.

So seems like a minor bug that probably won't affect many people, but thought you'd want to know what I just ran into.

**Comment by tanema** [comment] 2019-05-22 21:06
@idawgik Hello! I have gotten around to fixing this and I was wondering if you would be interested in using the v1.0.1-pre version for a while to test out for me.

You can try it out by running `theme update --version=v1.0.1-pre`. If you run `theme version` it will still say 1.0.0 but that is only because I did not update the version.

**Comment by tanema** [comment] 2019-06-19 14:43
This was fixed in 1.0.1 and it was released today

**Closed by tanema** 2019-06-19 14:43 UTC
Labels: :ship: pending next release
