### ISSUE TITLE
Theme Upload locales error

### ISSUE THREAD

**Issue by overturex** [Shopify/themekit#388] opened 2017-04-26 21:19 UTC
Hi There,

I am getting the following error when using Theme Upload.

Asset Perform Update to locales/zh_CN.json at host staging-ca-sengled-com.myshopify.com
        Status: 422 Unprocessable Entity
        Errors: Invalid locale name
                Key "Commands:" contains invalid characters
                Key "Options:" contains invalid characters
                Key "Examples:" contains invalid characters
                Key "default:" contains invalid characters
                Key "choices:" contains invalid characters
                Key "Not enough non-option arguments: got %s, need at least %s" contains invalid characters
                Key "Too many non-option arguments: got %s, maximum of %s" contains invalid characters
                Key "Missing argument value: %s" contains invalid characters
                Key "Missing required argument: %s" contains invalid characters
                Key "Unknown argument: %s" contains invalid characters
                Key "Invalid values:" contains invalid characters
                Key "Argument: %s, Given: %s, Choices: %s" contains invalid characters
                Key "Argument check failed: %s" contains invalid characters
                Key "Implications failed:" contains invalid characters
                Key "Not enough arguments following: %s" contains invalid characters
                Key "Invalid JSON config file: %s" contains invalid characters
                Key "Path to JSON config file" contains invalid characters
                Key "Show help" contains invalid characters

I don't even have `zn_CN.json` in theme's locales folder. Same error is also given for bunch of other locales files such as `locales/be.json`, `locales/zh.json`, `locales/tr.json` etc.

**Comment by tanema** [comment] 2017-05-01 13:13
Hey @overturex I have a few questions to figure this out. Does `locales/zh_CN.json` exist on your remote theme (the online editor)? Do any of those labels seem familiar? Does everything else success when uploading?

Can you also please email me at tim.anema@shopify.com your store domain and which theme you are developing with so I can test this out?

**Comment by tanema** [comment] 2017-05-01 18:22
Hey @overturex I contacted support to find your shop. I was unable to reproduce this bug. Are you sure that those file do not exist in your local development files. There seems to be no other reason why you would get this error. Theme kit recursively searches your files for items to upload. Do you still get the same error when you run `theme upload locales/*`

**Comment by tanema** [comment] 2017-05-10 22:48
Hey @overturex, I am just checking back in with this issue. If you can, please get in touch with me so I can resolve this issue.

**Comment by overturex** [comment] 2017-05-11 06:14
Hi @tanema. Nothing worked. The theme is in a git repo. I don't see any of those locale files in neither in my local nor it git. So, I decided to clone to repo to a new folder to test it and didn't get error this time. I still don't know what the problem was but it is working with the new clone now.

**Comment by tanema** [comment] 2017-05-11 13:02
Did you clone the first one from a repo or did you use `theme download` to get the code the first time.

**Comment by overturex** [comment] 2017-05-12 06:47
Cloned from a repo and was working fine before in terms of using `themekit`

**Comment by tanema** [comment] 2017-05-16 13:24
I am going close this since I cannot reproduce it and you can no longer reproduce it. There isn't really a possible way for random files to be uploaded so I am going to put this up to accidental bad setup or corrupted data from download. If this happens again and you can help me reproduce it please reopen.

**Comment by tbeseda** [comment] 2017-05-31 18:26
I also have this issue. It's not urgent since the rest of my theme is uploaded correctly. Just inconvenient to see a mess of errors.

From one local repo, across 4 themes on 2 different stores. (We test our theme in a few places with `$ theme replace --env=whatever` before deploying to production.)
Many 422 errors are returned during a replace. Mostly relating to locale files that are not in our local files or in any of the remote themes. There are also a few odd .tmpl files mentioned in the logs as well... weird.

It's been a year since we started the git repo, but I went back to the first commit and these files didn't exist then either.
We didn't use `theme download` to fetch the initial version. I believe we initially used the "Download theme file" option in the ourstore.myshopify/admin/themes to grab a theme we bought.

Not sure if it's relevant but we had been using the theme Ruby gem previously to themekit's release, but I know a developer or 2 that have started fresh on a new machine without the gem and cloned a fresh copy of the repo.

I have not personally tried what the OP did and clone the repo into a new directory.
Any other info I can provide?

Thanks!

**Comment by tbeseda** [comment] 2017-05-31 18:28
ping @tanema in case you don't get notifications on closed issues 🙊

**Comment by tanema** [comment] 2017-05-31 18:31
Hey @tbeseda thanks for pinging me. This is happening in multiple projects for you? Does it only happen with replace and not upload? These files do not exist on your remote theme?

**Comment by tbeseda** [comment] 2017-05-31 18:50
It happens in one project, but that same project goes to 2 themes in a "development" shop and 2 themes in a "production" shop. All produce the same 422 errors.

I just tried theme upload and got the same result as theme replace.

Correct, these files do not exist in the remote theme. Here's a mostly empty locales directory in the admin:
![image 2017-05-31 at 12 41 26 pm](https://cloud.githubusercontent.com/assets/15697/26648159/c7d28fda-45fe-11e7-885c-9dd6bb3db115.png)

In addition to the locale errors mentioned earlier, I get some similar to:
```
[development]Asset Perform Update to templates/directives/bs-switch.html at host <our-dev-shop>.myshopify.com
        Status: 422 Unprocessable Entity
        Errors: Theme files may not be stored in subfolders
```
We've never placed a sub directory in templates (though, that would be cool 😎). And we've never used a file named bs-switch.html. Maybe an old theme we had installed did?

Oh, also, I am using Windows 10, in case that is relevant.

**Comment by tanema** [comment] 2017-05-31 18:56
That is really confusing upload just looks for files from the filesystem, there is no cache to it. What themekit version are you on?

**Comment by tbeseda** [comment] 2017-05-31 19:18
```
----------------------------------------------------------------
        ThemeKit - Shopify Theme Utilities 0.6.12
----------------------------------------------------------------
```
Also, I looked for hidden files on my machine; no luck. Same as what I see in my editor, in Shopify admin, and in File Explorer.

I asked another theme dev who works on the same project, and she sees the same problem on her Mac.

**Comment by tbeseda** [comment] 2017-05-31 19:48
I re-cloned our repo and ran `theme replace` -- it worked! no errors!
But I noticed the file count was different. 
I realized the only different between the 2 folders was that I hadn't run `npm install` on the new location. So there was no node_modules folder yet.
I deleted the modules folder from my original project and ran theme replace again. No errors.

I reinstalled the node modules and added an ignore to my config.yml
```
ignore_files:
- /node_modules/
```
That did the trick.
I found a directory called locales with a bunch of .json files in one of the node_mdules sub directories. Must have matched a pattern in themekit.

I should have thought of that first. Thanks for the patience here.  
Maybe there should be some default ignores? I'd imagine ./.git/ is ignored already.

**Comment by tanema** [comment] 2017-05-31 19:52
oh! Good find! Right now default ignores are 

```
\.git
\.hg
\.bzr
\.svn
_darcs
CVS
\.sublime-(project|workspace)
\.DS_Store
\.sass-cache
Thumbs\.db
desktop\.ini
config.yml
```

So I can add node_modules to this list as well. However I think that this has exposed that the path matching to make sure a file is in a correct project directory is not properly matching as well. I will have to look into that.

**Comment by tanema** [comment] 2017-05-31 19:53
pinging @overturex for update on this issue.

**Comment by overturex** [comment] 2017-06-01 00:01
Good find @tbeseda. Probably one of the npm modules I was testing created the issue for my project.

Only if there was a way to pull directly from a git repo. I find that uploading directly from a local machine may cause issues like this. You might as well add `npm-debug.log` and `.idea` to default ignores.

I also really don't like the fact that `theme update` uploads all the files from my local to Shopify servers instead of getting the difference. Is there a better way?

**Comment by tanema** [comment] 2017-06-01 00:24
@overturex please follow along with this issue https://github.com/Shopify/themekit/issues/330 for making sure only the difference is changed.

**Closed** 2017-06-21 15:38 UTC
