### ISSUE TITLE
Hide password on config.yml

### ISSUE THREAD

**Issue by luiscoms** [Shopify/themekit#879] opened 2020-12-22 14:32 UTC
I want to use environment variable `THEMEKIT_PASSWORD` in order to do not commit the config.yml with password after run `theme` commands.

When I run `theme get` for example, the file `config.yml` is replaced with passoword set on `THEMEKIT_PASSWORD`

```
$ theme version
ThemeKit 1.1.4 darwin/amd64
```

**Comment by tanema** [comment] 2021-01-04 14:11
duplicate of https://github.com/Shopify/themekit/issues/639

**Closed by tanema** 2021-01-04 14:11 UTC
