### ISSUE TITLE
compiling sass into styles.scss.liquid

### ISSUE THREAD

**Issue by jrdnndtsch** [Shopify/themekit#234] opened 2016-10-27 17:05 UTC
I am using compass to compile sass and then update the styles.scss.liquid file. Themekit receives a Remove event and instead of updating removes the entire styles.scss.liquid file from the online store.

**Comment by tanema** [comment] 2016-10-27 17:27
duplicate of #233

**Closed by tanema** 2016-10-27 17:27 UTC
