### ISSUE TITLE
Theme Replace Not Replacing

### ISSUE THREAD

**Issue by chryton** [Shopify/themekit#393] opened 2017-05-15 19:52 UTC
TK Version: `0.6.11`
Platform: `OSX 10.12.4` and `OSX 10.11.5`
Shell: `oh-my-zsh` and `bash`

We've begun seeing a very odd issue where `theme replace` is not updating random files even though the command output is saying it is. If we run `theme upload` or `theme replace folder/file-name` instead, the files are correctly updated. This has happened on 4 separate occasions over the past month on the same store but uploading from different machines. The files affected each time are different but are affected the same way each time.

We have reached out to our Plus rep and support (Luke B) who said that it was probably a ThemeKit issue so we have done some extra digging on our part to try and narrow things down and confirm it is something to do with ThemeKit. 

Here are the test cases we've tried:
- Switching between ZSH & Bash
- Different machines (OSX 10.12.4 and 10.11.5)
- Different Themes uploaded to
- Different Themes downloaded from
- Order of operations of download and upload/replace
- Verifying all files in VCS (Git) before and after upload

**Comment by tanema** [comment] 2017-05-15 20:02
So these files are consistently not replacing or it randomly will not replace these file? What are your ignores because this sounds like an `ignored_files` issue.

**Comment by chryton** [comment] 2017-05-15 20:50
We looked at ignores but the files are not encapsulated by those:
```
  ignore_files:
    - "node_modules/*"
    - "src/*"
    - "*.html"
    - .jshintignore
    - .eslintrc.json
    - "*.sublime-workspace"
    - "*.sublime-project"
    - "package.json"
```

It is consistently not replacing the files when doing `theme replace` without a path/file; if we target just that file, it works as expected. `theme upload` without a path works as intended, however. The other weird thing is that of the 4 times this has happened, it has been different sets of files.

**Comment by tanema** [comment] 2017-05-15 20:54
can you give me some example paths that are exluded like `templates/layout.html.liquid`?

**Comment by chryton** [comment] 2017-05-15 21:07
Of course:

```
config/settings_schema.json
layout/checkout.liquid
snippets/product-details.liquid
snippets/sidecart.liquid
```

We don't seem to have the problem with any files within assets.

**Comment by tanema** [comment] 2017-05-15 21:08
Thanks I will take a look into it.

**Comment by chryton** [comment] 2017-05-15 21:22
@tanema If you need any access to test, email me at mauney@rocketcode.io .

**Comment by tanema** [comment] 2017-05-16 20:39
Hey @chryton do you see the filenames output when you do `theme replace --verbose`? I am wondering if the requests are being made at all or if the request is being made then it fails some how.

**Comment by chryton** [comment] 2017-05-17 14:21
Yes, we see the filenames and they upload without an error in verbose.

**Comment by tanema** [comment] 2017-05-17 14:22
Okay that is a critical but worrisome bit of information!

**Comment by tanema** [comment] 2017-05-24 16:38
So I am following up here for posterity. In trying to figure this out @chryton mentioned that he does a `replace` then `download` and uses git to diff it. 

I have an unconfirmed suspicion that this may be because caching of those files are not yet cleared so when you run download immediately after a `replace` some of the files downloaded are from cache and are the old versions. This will need to be confirmed.

**Comment by chryton** [comment] 2017-05-24 17:44
Would that also be the reason why the admin shows the old files?

**Comment by tanema** [comment] 2017-05-24 17:54
I am not sure I will need to try and test this, but yes this could be a possibility.

**Comment by tanema** [comment] 2017-06-21 17:09
Okay I talked to the themes team and they doubt it is a caching issue because the cache should not effect the admin. I will contact you soon with setup steps for `mitmproxy` so that we can log and save all the network requests and see what has happened.

**Comment by tanema** [comment] 2017-08-29 15:58
As of today on the new version it seems like this ran without problem. Since it happened pretty reliably on every previous deploy, I am closing this as fixed now but if on a future deploy it happens again please re-open the issue.

**Closed by tanema** 2017-08-29 15:58 UTC
