### ISSUE TITLE
0.7.x doesn't download or upload correctly depending on the environment

### ISSUE THREAD

**Issue by mimo84** [Shopify/themekit#461] opened 2017-08-31 23:54 UTC
### What I expected to happen
Running `theme download --env staging config/settings_data.json` should download the file coming from the store flagged as `staging` in the config.yml file.
Running `theme upload --env staging` should upload correctly the files.

### What actually happened
`theme download --env staging config/settings_data.json` downloads the file from the first in the list .
`theme upload --env staging` doesn't upload the files correctly. In fact it only uploads three files and the new/updated ones are not touched.

Downgrading to 0.6.12 fixes the issue.

### My Environment

OS (including version): OSX, Ubuntu
Themekit version: 0.7.3
Ignore Files(if any):

**Comment by tanema** [comment] 2017-09-01 15:09
What list are you referring to when you say:

> theme download --env staging config/settings_data.json downloads the file from the first in the list

Are you also aware that 0.7.x will skip files that are not updated. You are certain that these files were updated?

Can you please provide me with steps to reproduce this.

**Comment by mimo84** [comment] 2017-09-03 23:26
I refer to the `config.yml`.
Yes I am certain that these files where changed, in fact downgrading to 0.6.12 uploaded the files correctly.
The deployment is done through CircleCI on a fresh git clone and themekit install, so I would expect that all the files are uploaded.

**Comment by tanema** [comment] 2017-09-08 19:53
Hey @mimo84 can you install this patched version and verify that it works as you would expect it to? You can install it by running `theme update --version=v0.0.0-rc0.7.4`

**Comment by mimo84** [comment] 2017-09-13 03:45
The file seem to have been uploaded correctly with the environment as specified in the config.yml.

**Comment by mimo84** [comment] 2017-09-13 04:01
I think that since the new feature tries to be smart and figure out which files have been updated or not, the files are not correctly updated. What I need to do to make it work fine is to delete the theme.lock file every time or I continuously get 409 conflict errors even if the files have actually no difference in content.

**Comment by mimo84** [comment] 2017-09-13 05:13
To better explain what happens this is a screenshot of what I get while working on a theme:
<img width="837" alt="themekit-conflict" src="https://user-images.githubusercontent.com/1006473/30360630-f68b7a64-9895-11e7-8cfa-fb07247c96bb.png">

No modifications were made on remote.

**Comment by tanema** [comment] 2017-09-13 13:24
Now you are showing me the watch command though, I think this is related to #460 and one of the developers in that issue found that this was fixed after updating to the patched version and deleted the `theme.lock`

**Comment by mimo84** [comment] 2017-09-13 22:02
Thanks @tanema, the file download seems fixed but not the upload. I had a read of #460 and I see a different result. Even if I delete the `theme.lock` file the issue randomly reappears after a while (within 30 minutes)

**Comment by neycodes** [comment] 2017-09-15 08:25
Not sure if I should start a separate issue, but would it be possible to make use of the theme.lock optional?

I work in a team and everyone on the team is getting these 409 errors as well as merge conflicts in the theme.lock file every time we do a git pull.

We have now added theme.lock to .gitignore, which solves the git issue, but we're still dealing with the 409 errors when one of the team has made changes and uploaded to the theme.

**Comment by tanema** [comment] 2017-09-15 13:11
@neycodes Yeah I will add config in the future to disable it. You can roll back to v0.6.7 if this is stopping you. However I need to get this fully functional before I let everyone opt out because otherwise no one will use it ever and there might as well be no reason to update to the newer version. I apologize for my slowness in fixing these issue, I will get to it as soon as I have time.

**Comment by tanema** [comment] 2017-09-18 18:20
Since you started mention 409s from watch I am going to close this in favour of #460

**Closed** 2017-09-18 18:20 UTC
