### ISSUE TITLE
Newest Release does not show files missed in Theme Deploy (replace)

### ISSUE THREAD

**Issue by NewWorldOrderly** [Shopify/themekit#570] opened 2018-09-06 23:00 UTC
### What happened
Updated to latest version and now seem to get a number of files not making it onto Shopify during Theme Deploy or Theme Replace.

### What I expected to happen
Previously in the PowerShell window I would see the file name of any files that failed to upload. Now I only see the number of the file, but not the name, so impossible to know what file it was.

Also, seems to have trouble making a clean replace now, but before this was a rare issue. 

### My Environment

OS (including version): Windows 10
Themekit version: 0.8.0
Ignore Files(if any):

I have reverted back to 0.7.5 using the command below and everything works great. Also noticed that Theme Deploy from 0.8.0 wants to upload a lot more files than Theme Replace from 0.7.5. Not sure why this would be different. I am running the command from the same Theme directory

`theme update --version=v0.7.5`

**Comment by tanema** [comment] 2018-09-07 12:43
> Theme Deploy from 0.8.0 wants to upload a lot more files than Theme Replace 

This is a known bug in 0.8.0 because of windows paths, you can fix this by running `theme update --version=0.8.1-prerelease`

There is also a known bug https://github.com/Shopify/themekit/issues/562 that errors are no appropriately being output currently. To see them you can just run the command with the verbose flags. This is because the progress bar is overwriting the error output.

**Comment by tanema** [comment] 2018-09-12 14:19
Closing as this is a duplicate of 2 separate issues.

**Closed by tanema** 2018-09-12 14:19 UTC
