### ISSUE TITLE
Theme download doesn't work in 0.6.2

### ISSUE THREAD

**Issue by konung** [Shopify/themekit#307] opened 2017-01-04 18:50 UTC
Reverting to 0.6.1 works. 
Tried on Windows 10 & 7 - same issue. ( Using powershell inside ConEmu) 

Please let me know if you need additional debugging info.

**Comment by tanema** [comment] 2017-01-04 21:33
duplicate of #305

**Closed by tanema** 2017-01-04 21:33 UTC

**Comment by tanema** [comment] 2017-01-04 23:08
The new release 0.6.3 should fix this, sorry about the inconvenience.
