### ISSUE TITLE
theme deploy updates ignored files

### ISSUE THREAD

**Issue by mattAux** [Shopify/themekit#627] opened 2019-04-01 22:45 UTC
**config.yml**
Simplified filenames & hid passwords / store names
```
development:
  password: xxxxxxxxxxxx
  theme_id: "xxxxxxxxx"
  store: dev.myshopify.com
  ignore_files:
    - config/settings_data.json
    - snippets/foo-config.liquid
    - snippets/foo.liquid
production:
  password: xxxxxxxxx
  theme_id: "xxxxxxxxx"
  store: live.myshopify.com
  ignore_files:
    - config/settings_data.json
    - snippets/foo-config.liquid
    - snippets/foo.liquid
```

**To Reproduce**
1. add test text to section you wish using shopify -> themes -> customize, which should update settings_data.json on the store ( not local files )
2. run command 'theme deploy' ( in my case - 'theme deploy --env=production' )
3. check test section & it has been over written by the local settings_data.json ( generally outdated )

**Expected behavior**
If a user has updated a section ( live settings_data.json ), using theme deploy should not overwrite the section changes with outdated settings_data.json if it is included in the "ignored_files" in config.yml - where in fact it is not being ignored & the changes made by user are overwritten.

**Environment:**
 - OS: macOS Mojave 10.14.3 & Ubuntu 18.04.1 lts
- Themekit version: ThemeKit 1.0.0 darwin/amd64 & ThemeKit 1.0.0 linux/amd64
 - Editor: Atom & Visual Studio Code

**Additional context**
Essentially, client updated a section. Then I deployed code updates & their changes were overwritten by my deployment even though settings_data.json is "ignored" correctly.

**Comment by tanema** [comment] 2019-04-02 13:56
Hey @mattAux! Thanks for reporting this. I cannot reproduce this, however. Can you run your deploy command with the `-v` flag to ensure that it is getting deployed as you are experiencing? Also is there anything else in your config that may be missing from your example like directory config?

I have a suspicion that something else might be going on here because if this was broken I would have a lot more reports of it. This is a common workflow for most people using themekit and when this has broken in the past, the issue was opened within moments of my deploy. Although I have broken it in the past so it is possible :D

**Comment by mattAux** [comment] 2019-04-02 22:06
Hey @tanema, thanks for getting back to me so soon. 

I just ran the addition to deploy command & it didn't seem to deploy the ignored files -- I'm wondering if this was just some one off? I'm now unable to recreate the issue as well!

My apologies for the hassle & thank you for the support!!

**Comment by tanema** [comment] 2019-04-03 12:49
Do you have another person working on the same shop who might have uploaded the changes? Either through themekit accidentally or a person who used the online editor? There is also a `--no-ignore` flag however I think it is really unlikely that you used that flag without noticing.

**Comment by mattAux** [comment] 2019-04-03 20:32
There are two dev's working on the project, we have both run the command & the ignored settings_data.json file was not deployed with the `-v` flag.

We also have another person who updates content via the shopify admin panel - I'm under the impression the fault is at their end.

My apologies & thank you for your assistance!!
ThemeKit rocks!

**Comment by tanema** [comment] 2019-04-04 00:12
Thanks for the follow-up! I am going to go ahead and close this but feel free to re-open or open a new issue if you have any further issues.

**Closed by tanema** 2019-04-04 00:12 UTC
