### ISSUE TITLE
High CPU load on theme watch

### ISSUE THREAD

**Issue by jhavn** [Shopify/themekit#849] opened 2020-11-25 08:52 UTC
**Describe the bug**
I've noticed that lately - immediately after running theme watch - there's a huge CPU load. It's almost at 100%... 
Does anyone else have this issue? 

**To Reproduce**
1. run command 'theme watch'

**Expected behavior**
High CPU load when checking activity monitor. 

**Environment (please complete the following information):**
 - OS [e.g. iOS]: MacOS Catalina 10.15.7 on a 16 inch Macbook Pro (2019). 
- Themekit version (run theme version to check): 1.1.2
 - Editor [e.g. atom, sublime]: VS Code 

**Additional context**
Downgraded from Big Sur to Catalina (clean install) because I thought the issue was with Big Sur. Did a clean install.

Now it seems that the issue has something to do with themekit.

**Comment by andyw8** [comment] 2020-11-25 14:23
Hi @jhavn, how many files are your theme directory?

**Comment by jhavn** [comment] 2020-11-25 14:52
Hello @andyw8! How can I check how many files I have in my theme directory?

**Comment by tanema** [comment] 2020-11-26 16:08
duplicate of https://github.com/Shopify/themekit/issues/664

**Closed by tanema** 2020-11-26 16:08 UTC
