### ISSUE TITLE
Timeout Issue

### ISSUE THREAD

**Issue by burakswe** [Shopify/themekit#665] opened 2019-10-08 10:39 UTC
**Describe the bug**
Hi, when I type `theme watch`, I ran into some issues. I can't track the files. This is what I get: 
`request timed out. if you are receive this error consistently, try increasing the timeout in your config`

Hope you can help me. 
Thanks!

**Environment :**
 - OS [macOS Mojave]:
- Themekit version [1.0.1]:

**Comment by tanema** [comment] 2019-10-08 14:18
Did you increase your timeout?
What do you mean you cant track the files

**Comment by burakswe** [comment] 2019-10-09 07:26
@tanema Thanks for your reply. I mean, I can't upload my files via Themekit
I've already increased timeout, set '180s'.

**Comment by tanema** [comment] 2019-10-09 14:56
both `theme watch` and `theme deploy` do not work and give you this timeout issue?

**Comment by burakswe** [comment] 2019-10-10 08:34
Yes, correct, but recently I increased the timeout value up to '10000s' and now I'm able to upload and watch my files, however I sometimes experience the same issue. When I save my files, sometimes it doesn't upload the files and give the same error above.

**Comment by tanema** [comment] 2019-10-10 14:38
How about`theme download`? It seems like you have connection issues. Are you behind a proxy or a firewall?

**Comment by tanema** [comment] 2020-02-06 15:33
I am starting to put things together and this seems like a duplicate of https://github.com/Shopify/themekit/issues/685 because of the check for updates to themekit at startup

**Comment by tanema** [comment] 2020-02-06 15:37
Sorry I meant duplicate of https://github.com/Shopify/themekit/issues/665

**Comment by lmartins** [comment] 2020-02-26 18:53
@burakswe are you still seeing this issue? I use to get this problem once in a while, it now happens every single time, no matter what value I set the timeout to be.

**Comment by burakswe** [comment] 2020-02-26 19:33
@lmartins I'm still seeing the issue. If I experience the issue too much in a day, I'll use the customizer of Shopify.

**Comment by tanema** [comment] 2020-02-26 19:48
Can either of you send me the shop domains that you are working on so that I can check the logs? email me at tim [dot] anema [at] shopify [dot] com

**Comment by lmartins** [comment] 2020-02-26 19:53
@tanema thank you so much for looking into this. Having just dropped Slate for Themekit you can't imagine how worried this whole thing is making me.

I've just sent you the info via email.

**Comment by lmartins** [comment] 2020-02-27 17:09
@tanema Tim, sorry to reach out but were you able to see anything suspicious from your end that could help resolve this issue? All commands still pretty much useless for me, they all timeout, after just a few seconds, no matter how big the timeout I put in with config or inline params.

What's strange about it, is that the command times out always around the same amount of time, no matter the timeout value I pass to it, so it is also almost like it is taking no effect at all. But regardless, the time it takes to timeout used to be enough for the command to start successfully.

**Comment by tanema** [comment] 2020-02-27 18:52
I checked the logs and I see activity on your shop however nothing other than 200 http statuses and responses under 8ms. Can you try a different network? Just to give you clarity as well, slate was all built on top of themekit, you have been using themekit this whole time as well. Maybe try downgrading themekit to see if there is a version that it works better for you. You can do this by running `theme update --version=v1.0.0`

**Comment by lmartins** [comment] 2020-02-27 19:03
@tanema I do have a colleague running `1.0.1` on the same network who can run it successfully.

When I try to run the update command, here's what I get:

```
theme update --version=v1.0.0 
Updating from 1.0.2 to v1.0.0
Get https://shopify-themekit.s3.amazonaws.com/releases/all.json: net/http: TLS handshake timeout
```
Related to the other issue?

**Comment by tanema** [comment] 2020-02-27 19:28
It is possible yes, but you dont find that it fixes your problems to run themekit commands with the `--no-update-notifier`?

**Comment by lmartins** [comment] 2020-02-27 19:33
Sadly no, even with the `--no-update-notifier` flag it times out after just a few seconds too. :(

**Comment by tanema** [comment] 2020-02-27 21:49
Did you install it with homebrew? Can you try switching the version to 1.0.0 with hombrew?
 
You can do that by installing via the old formula.
```bash
brew unlink themekit
brew install https://raw.githubusercontent.com/Shopify/homebrew-shopify/7c68b8d16a14d8cdd761e855dccc17881bbecfc0/themekit.rb
```

**Comment by lmartins** [comment] 2020-02-29 11:57
@tanema so sorry, I've missed your latest comment above. 
I'm pleased to say that running your test above did the trick for me though. Downgrading to 1.0.0 gets the watcher again without any timeouts. 

I should say that I have another Mac on this same network, also running themekit 1.0.3, and on that machine I can get `theme watch` running without any issues, so I really don't know what is that about. For now this allows me to keep, which I'm deeply grateful for, as a I am to you and your help here.

**Comment by tanema** [comment] 2020-03-01 16:31
If that solved it I have a suspicion about the go version and I also disabled CGO in 1.02 so that may cause connection issues for some reason. I will have to look around to see if there were any issues opened on the Go repo related to this

**Comment by lmartins** [comment] 2020-03-02 09:36
Thank you @tanema 
Once useful for you for me to upgrade and test again please let me know. For now I'll keep on 1.0 so I'm able to use the tool again.

**Comment by wojtekdmyszewicz** [comment] 2020-06-02 10:30
Make sure you're not behind a proxy or connect via vpn

**Comment by lmartins** [comment] 2020-06-02 13:15
While that may be the case for some, that ain't the case for here. And it still happening.

**Comment by tobiasger** [comment] 2020-07-29 09:00
I have this issue right now running `theme watch`. Has worked without any issues at all for several weeks until now. Haven't updated or changed the version of Themekit.

**Comment by tobiasger** [comment] 2020-08-05 13:45
Turns out that my problem was occuring because of an unstable WiFi connection, so please ignore my previous message.

**Closed** 2020-08-20 20:29 UTC
