### ISSUE TITLE
Recent versions have caused significant slow down

### ISSUE THREAD

**Issue by adrianocr** [Shopify/themekit#874] opened 2020-12-08 20:00 UTC
**Describe the bug**
The last few updates to themekit (I'd say give or take the last 3 or 4), since when you guys added file hash checking to only sync changed files, has caused themekit to slow down significantly. It is RARELY ever below 55% CPU utilization on my machine. 

**To Reproduce**
Use latest themekit, `theme watch`, monitor system resources

**Expected behavior**
I'd like it to work like it did before. It used to rarely ever go over ~15% CPU utilization and `theme watch` didn't cause my entire machine to slow to a crawl.

**Environment (please complete the following information):**
 - OS: macOS Big Sur, late 2013 MBP 15" Intel i7, 16 GB RAM
- Themekit version: ThemeKit 1.1.4 darwin/amd64
 - Editor: VS Code
 - Ignore: ./config/

**Comment by tanema** [comment] 2020-12-09 22:32
I think this is a duplicate of #664 please add any information there that you think has not been captured. The hashing only happens on file events, is there something on your machine that might be touching files even though they have not changed?

**Closed by tanema** 2020-12-09 22:32 UTC
