### ISSUE TITLE
theme watch doesn't work in 0.62 (Windows)

### ISSUE THREAD

**Issue by sarhov** [Shopify/themekit#308] opened 2017-01-04 21:31 UTC
theme watch doesn't work in version 0.62, nothing is happening after save, I rolled back to 0.61 and it worked

**Comment by tanema** [comment] 2017-01-04 21:33
duplicate of #305

**Closed by tanema** 2017-01-04 21:33 UTC

**Comment by tanema** [comment] 2017-01-04 23:09
The new release 0.6.3 will fix this, sorry about the inconvenience.
