### ISSUE TITLE
'Deploy' replacing everything, not just updated local files

### ISSUE THREAD

**Issue by jimmyfisher** [Shopify/themekit#572] opened 2018-09-10 17:36 UTC
### What happened
I updated Themekit to 0.8 and ran the normal `theme deploy -v` command (I had been using `theme replace -v` in 0.7.5. My entire Shopify site uploaded to the server even though only certain items had been changed.

### What I expected to happen
In 0.7.5, when I run this command, I get a list of files all saying 'skipping Update of' followed by the file. I assume it's seeing that there were no local changes. Only the files with local changes get uploaded to Shopify.

### Steps to reproduce

1. Updated Themekit to 0.8
2. Ran `theme deploy -v`
3. Every file of the site started to upload rather than just the ones that changed locally

### My Environment

OS (including version): macOS Sierra 10.12.6
Themekit version: 0.8 (I've downgraded back to 0.7.5 since the behavior seemed to come from the update)
Ignore Files(if any):

**Comment by tanema** [comment] 2018-09-10 18:11
duplicate of https://github.com/Shopify/themekit/issues/540

**Closed by tanema** 2018-09-10 18:11 UTC
