### ISSUE TITLE
Saving firing remove event before update event when in Vim

### ISSUE THREAD

**Issue by colindresj** [Shopify/themekit#510] opened 2018-03-10 20:42 UTC
### What happened
Saving fires a remove event before subsequent save fires an update event

### What I expected to happen
Saving fires only an update event

### Steps to reproduce
1. run `theme watch -n .tk_update`
2. make changes to a theme file and save
3. output reads `[development] Received Remove event on <your-file>.liquid`
4. save again
5. output reads `[development] Received Update event on <your-file>.liquid`

### My Environment

OS (including version): OSX Sierra
Editor: Vim 8.0.1175
Themekit version:  0.7.5
Ignore Files(if any):
- package.json
- yarn.lock
- README.md

Relates to #168 and #188

**Comment by tanema** [comment] 2018-03-12 13:55
What editor are you using?

**Comment by colindresj** [comment] 2018-03-14 00:50
I'm using vim

**Comment by colindresj** [comment] 2018-03-14 01:01
I've confirmed that the bug I've reported doesn't happen when running in Atom or text edit (that's all I have to test on)

**Comment by wiznia** [comment] 2018-03-19 20:49
I can confirm the same problem on my end, also using vim. It doesn't happen on Sublime Text.

**Comment by tanema** [comment] 2018-03-19 20:50
What is your vim version? I am wondering if a new update to Vim causes it to swap files slower.

**Comment by wiznia** [comment] 2018-03-19 20:52
I'm using nvim. Problem seems to be related to the saving strategy.

Using `:set backupcopy=yes` seems to fix the problem on all files except *.scss files.

**Comment by tanema** [comment] 2018-03-19 20:55
Yes, vim has this problem because of the way it uses swap files. In the past I tweaked the debouncing of events to make sure that the remove event doesn't happen.

**Comment by tanema** [comment] 2018-08-22 14:55
@wiznia @colindresj Please upgrade to v0.8.0 and try to reproduce this. I am running vim 8.1 and not having these issues, with or without backupcopy. If you are still having issues, it may be a plugin so please start vim without any config using `vim --clean <filename>` and see if the problem still persists. Thank you!

**Comment by tanema** [comment] 2018-08-30 15:49
I am closing this because I believe this has been fixed in the newest version with updates to the file watcher. Please re-open if this is not the case.

**Closed by tanema** 2018-08-30 15:49 UTC
