### ISSUE TITLE
2016 Planning

### ISSUE THREAD

**Issue by chrisbutcher** [Shopify/themekit#128] opened 2015-12-21 19:34 UTC
- Error handling (more value to work on this in the short-term)
  - [x] Differentiate transient errors (500 etc) vs. abort-worthy errors (401 etc.).
    - If credentials are bad, do not report 401 on all failed requests, since all will fail
    - Methods should use builtin error return types
    - Example: https://golang.org/pkg/net/http/#pkg-variables
  - [x] Better reporting for invalid/deprecated configuration
- Configuration:
  - [x] Use globs for filename/extension includes and excludes (github.com/ryanuber/go-glob)
- Decouple CLI from library of commands
  - [x] Switch to https://github.com/spf13/cobra for better CLI
  - [x] Switch to https://github.com/spf13/viper for better config including ENV vars
- ThemeClient
  - [x] Decouple http requests, responses, some theme asset-specific methods from client that communicates with Shopify.
- Releasing (https://github.com/Shopify/themekit/issues/146)
  - [x] Come up with way to release unstable versions to test new CLI/configuration stuff
  - [ ]  Improve curl / pipe installation script
  - [ ] HomeBrew formulae
  - [ ] Linux apt package
  - [ ] [NSIS](https://en.wikipedia.org/wiki/Nullsoft_Scriptable_Install_System)
  - [ ] Gulp/Node pacakge
- Documentation
  - [x] flags (this may get better once we have cobra and the help output will be better (https://github.com/Shopify/themekit/issues/117)
  - [x] manual installation (https://github.com/Shopify/themekit/issues/107)
  - [x] ignore_files: specify that it is a glob not just straight file name warn about (https://github.com/Shopify/themekit/issues/126, https://github.com/Shopify/themekit/issues/211)
  - [x] timeout config is in nano seconds but can be set to seconds if set like `60s`

cc train! :train: @ilikeorangutans

**Comment by ilikeorangutans** [comment] 2015-12-22 18:02
To add to this, better checking for credentials in general and configuration validation. I think #119 is caused by missing/invalid credentials.

**Comment by chrisbutcher** [comment] 2016-01-04 18:20
@ilikeorangutans I've added some linked and suggestions with initials above.

**Comment by brettchalupa** [comment] 2016-06-22 22:28
In regards to:

> Switch to https://github.com/codegangsta/cli ?

It seems like https://github.com/spf13/cobra is another option worth evaluating. I haven't used Cobra, but it seems like some [popular CLIs use it](https://github.com/spf13/cobra/blob/master/README.md). I have used cli in the past and had a positive experience, but I thought cobra would be worth sharing as well. 😁

**Comment by ilikeorangutans** [comment] 2016-06-23 15:20
I've heard of cobra but haven't had a chance to try it. I'm game either way!

**Comment by tanema** [comment] 2016-11-07 15:30
I am closing this now because most of the tasks are done except for the install flow and there is a separate issue for that  https://github.com/Shopify/themekit/issues/146

**Closed by tanema** 2016-11-07 15:30 UTC
