### ISSUE TITLE
Unaltered lines marked as changed.

### ISSUE THREAD

**Issue by neycodes** [Shopify/themekit#252] opened 2016-11-10 17:25 UTC
If I change one line of code, multiple other lines are then marked as changed. Then if I undo the 1 change I made, the other lines are still marked as changed.

For example, I changed one word in "theme.liquid" and my editor (Atom) showed 81 lines added/81 lines deleted. Upon undoing the change, it showed 80 lines added/80 lines deleted.

Is this a problem with running `theme watch`?

**Comment by tanema** [comment] 2016-11-11 14:37
I don't think this is a problem with theme kit. I may be a plugin you have that is doing it however I won't dismiss it right away I will test a bit. I am working on better git integration right now anyways.

Do you a plugin to tell you what has changed? I don't use atom and when I open it I don't see that information anywhere.

**Comment by neycodes** [comment] 2016-11-11 14:43
I am running a plugin called [git-diff](https://github.com/atom/git-diff) in Atom to show new/edited lines in a file. It is possible that it's just glitching with tracking themekit changes.

**Comment by tanema** [comment] 2016-11-14 16:09
Hey @neycodes I have been testing with this and I have not found that it has marked more lines than have changed. I am going to close this since I cannot find a situation where this is the case. If however you can get me steps to full reproduce this and have it narrowed down to themekit then please reopen this issue and I will take care of this.

**Closed by tanema** 2016-11-14 16:09 UTC
