### ISSUE TITLE
Create theme from scratch - mime error!?

### ISSUE THREAD

**Issue by frontenden** [Shopify/themekit#612] opened 2019-01-30 19:07 UTC
So i created a new theme and used themekit to setup the theme locally. Works fine and i can edit the files. But when i try to edit my scss i get this error in the console 

"Refused to apply style from 'https://cdn.shopify.com/s/files/1/0175/8072/0228/t/2/assets/application.scss.css?3366955993252409450' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled."  

and css changes isnt applied. Everything else works fine. Frustrating!! SOS - anyone?

**Comment by tanema** [comment] 2019-01-30 19:18
Is this related to this other issue? https://github.com/Shopify/themekit/issues/609

**Comment by frontenden** [comment] 2019-01-31 06:36
Sure looks like it, i Will test when i get home tonight. Thanks for fast reply.

Sendt fra min iPhone

**Comment by frontenden** [comment] 2019-01-31 13:15
@tanema i still get the error. from scratch it looks like this: {{ 'application.scss.css' | asset_url | stylesheet_tag }} and if i rename to {{ 'application.scss' | asset_url | stylesheet_tag }} i still get the error as above just with another path.

Refused to apply style from 'https://cdn.shopify.com/s/files/1/0175/8072/0228/t/2/assets/application.scss?17368912163522712861' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

**Comment by tanema** [comment] 2019-02-01 01:10
closing because it is a duplicate of #609

**Closed by tanema** 2019-02-01 01:10 UTC
