### ISSUE TITLE
Theme deploy/replace stuck at 97% upload

### ISSUE THREAD

**Issue by jabel-riera** [Shopify/themekit#579] opened 2018-09-26 09:39 UTC
### What happened
Since I updated to the last version of ThemeKit yesterday, every time I try to deploy the theme I have been working with for the last 6 months gets stuck at 97%.

### My Environment
OS (including version): Mac OS X 10.13.4 (17E202)
Themekit version: ThemeKit 0.8.1 darwin/amd64
Editor (including version): ATOM 1.23.3

**Comment by tanema** [comment] 2018-09-26 13:14
It just hangs and does not complete?

**Comment by jabel-riera** [comment] 2018-09-26 13:34
yes, it just hangs and does not complete. No error message is shown. 

Thanks

**Comment by tanema** [comment] 2018-09-26 13:39
What are you ignored files and what is the exact command that you are running.  It would be helpful if you provided more information like:

- What I expected to happen
- Steps to reproduce
- Ignore Files config

**Comment by jabel-riera** [comment] 2018-09-26 14:17
I have not filled those sections because:

**What I expect to happen**: to reach 100% upload (obviously). 
**Steps to reproduce**: I just typed _theme deploy_
**Ignore Filres config**: There is no file ignored.

**Comment by tanema** [comment] 2018-09-26 15:30
Please run `theme deploy -v` to see the complete output and see if there is an error that is supressed. I will look into this shortly

**Comment by jabel-riera** [comment] 2018-09-27 06:48
I executed the `theme deploy -v` as requested. Output is a list of "Updated route/file.liquid" but all of a sudden it just hangs as previously described. No error message shown :/

Thanks @tanema

**Comment by tanema** [comment] 2018-09-28 19:07
While I was trying to figure out this other error https://github.com/Shopify/themekit/issues/577 I noticed that the command hung while trying to upload a compiled asset. I think that is what is happening for you as well. Does this sound  familiar?
For instance you have a file that was names `application.js.liquid` and then without themekit running you rename it to `application.js` and then try and deploy again. Does this sound familiar to what you have recently been working on?

**Comment by jabel-riera** [comment] 2018-10-01 07:01
Hi @tanema ! 

Sorry for my late reply and thank you very much for your time and effort on the issue. I have just had some minutes now to test what you asked for and it seems that now everything is running smooth!!

Have a great week!!

**Comment by tanema** [comment] 2018-10-01 14:17
Excellent, if that was your problem then I will close this issue and keep the other one open. This fix will be available in the next release but you can continue to use that prerelease until then.

**Comment by jabel-riera** [comment] 2018-10-01 14:34
I don't get it. Where do you see that "it was my problem then"? English is not my native language and maybe one of us have misunderstood the other one. What I meant in my "edit" was that when I used the code you provided it did not hang **but** it ignored some files, that is why it uploaded I imagine. In addition, those files were missing on our shopify store after it. All of them where .js.liquid, .scss.liquid or similar.

**Comment by tanema** [comment] 2018-10-01 14:58
I had figured they were missed and not uploaded because of this issue, my apologies for misunderstanding. If you run `theme deploy -v` to see all the complete operations do you see the filenames there? The .js.liquid files are on your machine but not on shopify? Are they on shopify but not updated? is there the same file on the server without the liquid extension? for instance is there a `app.js` AND `app.js.liquid`?

**Comment by jabel-riera** [comment] 2018-10-02 06:36
Once I have rolled back to 0.8.1 the files are there (on both shopify and local) but still hangs during the process. I will try with the prerelease later today if you want me to try it.

**Comment by tanema** [comment] 2018-10-02 14:12
yes please.

**Comment by ethansaks** [comment] 2018-10-02 19:36
@tanema I had this same issue and found this page from a google search. I upgraded to the prerelase you suggested and tried again. Everything worked fine.

**Comment by tanema** [comment] 2018-10-09 13:36
@jabel-riera Okay I am going to close this issue since the original root issue was fixed, however if you are still seeing issues with files being skipped, please open a new issue.

**Closed by tanema** 2018-10-09 13:36 UTC
