### ISSUE TITLE
When saving a very large CSS.liquid file the file gets cut off

### ISSUE THREAD

**Issue by amit0001** [Shopify/themekit#218] opened 2016-10-10 10:35 UTC
Hi,

I am using the standard configuration.

Sometimes, not sure exactly when but very often, the file upload gets stopped and the file only uploads partially. The file gets stuck in this state until I manually paste using the admin console.

Thanks
Amit

**Comment by tanema** [comment] 2016-10-11 13:39
Duplicate of https://github.com/Shopify/themekit/issues/200 I will be releasing 0.4.4 later today and that will fix your problem.

**Closed by tanema** 2016-10-11 13:39 UTC

**Comment by amit0001** [comment] 2016-10-13 08:13
Fixed. Thanks!
