### ISSUE TITLE
Configuration without theme ID defaults to live

### ISSUE THREAD

**Issue by EMachado88** [Shopify/themekit#689] opened 2020-02-18 16:03 UTC
When no theme_id (or an invalid value) is provided in config.yml, for a valid password, theme watch/deploy defaults to live theme.

**To Reproduce**
1. save config.yml with a valid block (password + store) and no theme_id (or invalid value, ex. [88262180909])
2. run 'theme deploy'

**Expected behavior**
Themekit should fail as falling back to live theme is a dangerous practice.
Imagine someone on your team configures a "faulty" config.yml and runs theme deploy, overriding the live theme.
IMO there should be no such fallback and configuration should only be valid with explicit theme ID.

**Environment:**
 - OS: MacOS Catalina v10.15.3
- Themekit: 1.0.3

**Comment by tanema** [comment] 2020-02-24 19:12
Okay, I am going to mark this as a duplicate of #670 as there is a theme of worry about accidental live theme editing. I will look into adding functionality to make it harder to edit a live theme

**Closed by tanema** 2020-02-24 19:12 UTC

**Comment by mitas1** [comment] 2020-03-17 18:07
I think #670 is not going to resolve this (maybe partially). I agree with @EMachado88 expected behavior, it definitely should NOT defaults to live theme! And please fix this asap, this is a serious bug...
