### ISSUE TITLE
Updated theme kit to 0.8.0 now my theme will not upload properly

### ISSUE THREAD

**Issue by eyekanspele** [Shopify/themekit#552] opened 2018-08-23 19:10 UTC
### What happened
I got a message that there was an update to theme kit, and to run "theme update" to get the latest (0.8.0)
Ran the update, and it seemed to install.

Now when I do theme deploy to deploy an entire theme, the file count seems to be completely wrong (way higher, and everytime I run the command i get a different count number), and not all the files are uploaded to me site. 

No errors are thrown.

I have tried this with different themes and sites, and all do not seem to work.

### What I expected to happen
running:
theme deploy

will give an accurate file count.
All files will be replaced on my shopify site.

### Steps to reproduce

1. set present directory to where you theme is located
2. have config.yml setup
3. run theme deploy

### My Environment

Themekit 0.8.0
Visual Studio Code

OS (including version): Windows 10 Pro x64 build 16299
Themekit version: 0.8.0
Ignore Files(if any): None

**Comment by eyekanspele** [comment] 2018-08-23 19:15
I also want to note, I foung theme.exe.old. 
I removed the updated 0.8.0 version of the exe, and renamed the .old file back to theme.exe.

Running theme replace works great.
This is for sure an issue with 0.8.0 only.

**Comment by tanema** [comment] 2018-08-23 19:52
Sorry this a bug in how version 0.8.0 handles windows filepaths. This is a duplicate of this issue: https://github.com/Shopify/themekit/issues/548

You can either upgrade to the prerelease with:
```
theme update --version=v0.8.1-prerelease
```

Or stay on 0.7.5 until 0.8.1

**Closed by tanema** 2018-08-23 19:52 UTC

**Comment by eyekanspele** [comment] 2018-08-23 20:36
Thanks for the fast reply.

I did not think to check to see if there were any closed issues, that were similar to mine.
