### ISSUE TITLE
"theme watch" not running, producting YAML error

### ISSUE THREAD

**Issue by tomhaddad** [Shopify/themekit#521] opened 2018-06-13 10:04 UTC
### What happened
Error produced in console: "YAML error: control characters are not allowed"
Tried regenerating config file with the same error occurring, looks like this (with personal data removed):
development:
  password: xxxxxx
  theme_id: "1234"
  store: example.myshopify.com

### What I expected to happen
Watch folder for changes and automatically upload as usual

### Steps to reproduce
1. Executed "theme watch" on a directory which has worked perfectly fine previously
2. Error produced in console: "YAML error: control characters are not allowed"

### My Environment
OS (including version): Windows 10
Themekit version: ThemeKit 0.7.5 windows/amd64
Ignore Files(if any): none

**Comment by tanema** [comment] 2018-07-17 12:37
This seems to be a duplicate of #526 but there is a suggestion of how to fix this in there so I will close this one in favour of the other.

**Closed by tanema** 2018-07-17 12:37 UTC
